apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/sunflowerdeath/dev/stickers-world/backend/test/
